### ISSUE TITLE
Crash with newest Bewitchment versions (9 and 10)

### ISSUE THREAD

**Issue by InsaanNotFound** [Aelpecyem/Besmirchment#5]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'besmirchment'!
    at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.6)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
    at net.minecraft.client.MinecraftClient.redirect$fbk000$stopFabricInit(MinecraftClient:20360)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:437)
    at net.minecraft.client.main.Main.main(Main:177)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
    at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoSuchMethodError: 'void moriyashiine.bewitchment.api.registry.Contract.<init>(boolean)'
    at de.aelpecyem.besmirchment.common.registry.BSMContracts.<clinit>(BSMContracts.java:7)
    at de.aelpecyem.besmirchment.common.Besmirchment.onInitialize(Besmirchment.java:32)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    ... 19 more

**Comment by Aelpecyem** [comment]
Besmirchent has not yet been updated to the latest Bewitchment version

**Comment by InsaanNotFound** [comment]
I guessed that, just reporting the incompability

**Comment by Aelpecyem** [comment]
nice
expect a build within the next two weeks or so idk
